<?php require_once "includes/header.php"; ?>

<?php require_once("classes/Constants.php"); ?>

<?php require_once("classes/Reports.php"); ?>

<?php require_once("classes/Payments.php"); ?>

<?php require_once('classes/OAuth.php'); ?>

<?php
    if(!$auth -> isLoggedIn()) {
        header(NOT_FOUND);
        die();
    }
	$api = 'https://demo.pesapal.com';
	$token = $params 	= NULL;
	$iframelink 		= $api.'/api/PostPesapalDirectOrderV4';

	//Kenyan keys
	$consumer_key 		= PESAPAL_CONSUMER_KEY;
	$consumer_secret 	= PESAPAL_CONSUMER_SECRECT;

	$signature_method	= new OAuthSignatureMethod_HMAC_SHA1();
	$consumer 			= new OAuthConsumer($consumer_key, $consumer_secret);

    if($auth -> get("buy-report") != null) {
        $reportId = $auth -> get("buy-report");
    } else {
        header(BASE_URL_REDIRECT);
        die();
    }

    // create report object
    $report = new Reports();
    $reportInfo =  $report -> getReport($reportId);
    $report = null;

    if(count($reportInfo) <= 0 || empty($reportInfo)) {
        header(BASE_URL_REDIRECT);
        die();
    }

    $user = $auth -> getUserDetails($auth -> get("user_id"));

    $payment = new Payments();

    //just to make sure when user refreshes page only one order is stored.. this will be cleard in redirect
    if($auth -> get("StoredReportId") != $reportId) {
        $ref = $payment -> generateReference($user["user_id"], $reportInfo["report_id"]);
        $auth -> set("ref",$ref);
        if($payment -> storeOrder($ref,$auth -> get("user_id"),$reportInfo["report_id"],$reportInfo["report_price"])) {
            $auth -> set("StoredReportId",$reportId);
        }
    }

	$amount 		= str_replace(',','',$reportInfo["report_price"]); // remove thousands seperator if included
	$amount 		= number_format($amount, 2); //format amount to 2 decimal places
	$desc 			= $reportInfo["report_title"];
	$type 			= 'MERCHANT';
	$first_name 	= $user["user_firstname"];
	$last_name 		= $user["user_lastname"];
	$email 			= $user["user_email"];
	$currency 		= "KES";
	$reference 		= $auth -> get("ref"); //unique transaction id, generated by merchant.
	$callback_url 	= BASE_URL . 'redirect.php'; //URL user to be redirected to after payment

	$post_xml	= "<?xml version=\"1.0\" encoding=\"utf-8\"?>
				   <PesapalDirectOrderInfo
						xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
					  	xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"
					  	Currency=\"".$currency."\"
					  	Amount=\"".$amount."\"
					  	Description=\"".$desc."\"
					  	Type=\"".$type."\"
					  	Reference=\"".$reference."\"
					  	FirstName=\"".$first_name."\"
					  	LastName=\"".$last_name."\"
					  	Email=\"".$email."\"
					  	xmlns=\"http://www.pesapal.com\" />";
	$post_xml = htmlentities($post_xml);

	//post transaction to pesapal
	$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
	$iframe_src->set_parameter("oauth_callback", $callback_url);
	$iframe_src->set_parameter("pesapal_request_data", $post_xml);
	$iframe_src->sign_request($signature_method, $consumer, $token);

?>

<div class="content-header-industry">
	<?php include "includes/desktop-nav.php" ?>
	<?php include "includes/mobile-nav.php" ?>
</div>


<div class="container payment-container">
    <h5>Checkout</h5>
    <hr>
    <div class="row">
        <div class="col-lg-6">
            <iframe src="<?php echo $iframe_src;?>" width="100%" height="700px"  scrolling="no" frameBorder="0">
                <p>Browser unable to load iFrame</p>
            </iframe>
        </div>
        <div class="col-lg-6">
            <h6>Report information</h6>
            <hr class="blue-hr">
            <h5><?php echo $reportInfo["report_title"]; ?></h5>
            <p><?php echo $reportInfo["report_overview"]; ?></p>
            <h6 class="report-author">By <?php echo $reportInfo["report_author"]; ?></h6>
            <h4 class="report-price">KES: <?php echo number_format($reportInfo["report_price"]); ?></h4>
            <h6 class="promo"><i class="fa fa-check" aria-hidden="true"></i> Use however you want</h6>
            <h6 class="promo"><i class="fa fa-check" aria-hidden="true"></i> Yours forever</h6>
            <h6 class="promo"><i class="fa fa-check" aria-hidden="true"></i> Support guaranteed</h6>
        </div>
    </div>
</div>


<?php require_once "includes/footer.php"; ?>
