<?php require_once("header.php"); ?>

<?php require_once("classes/Constants.php"); ?>

<?php require_once("classes/Reports.php"); ?>

<?php require_once("classes/Payments.php"); ?>

<?php require_once('classes/OAuth.php'); ?>

<?php

	 if(!$auth -> isLoggedIn()) {
        header(NOT_FOUND);
        die();
    }

	$api = 'https://demo.pesapal.com';

	$token = $params 	= NULL;

	$iframelink 		= $api.'/api/PostPesapalDirectOrderV4';

	//Kenyan keys
	$consumer_key 		= PESAPAL_CONSUMER_KEY;
	$consumer_secret 	= PESAPAL_CONSUMER_SECRECT;

	$signature_method	= new OAuthSignatureMethod_HMAC_SHA1();
	$consumer 			= new OAuthConsumer($consumer_key, $consumer_secret);

    if(isset($_POST["r_id"]) && is_numeric($_POST["r_id"])) {
        $reportId = $_POST["r_id"];
    } else {
        header(BASE_URL_REDIRECT);
        die();
    }

    // create report object
    $report = new Reports();

    $reportInfo =  $report -> getReport($reportId);

    $report = null;

    if(count($reportInfo) <= 0 || empty($reportInfo)) {
        header(BASE_URL_REDIRECT);
        die();
    }

    $user = $auth -> getUserDetails($auth -> get("user_id"));

    $payment = new Payments();

    $ref = $payment -> generateReference($user["user_id"], $reportInfo["report_id"]);

	$amount 		= str_replace(',','',$reportInfo["report_price"]); // remove thousands seperator if included
	$amount 		= number_format($amount, 2); //format amount to 2 decimal places
	$desc 			= $reportInfo["report_title"];
	$type 			= 'MERCHANT';
	$first_name 	= $user["user_firstname"];
	$last_name 		= $user["user_lastname"];
	$email 			= $user["user_email"];
	$currency 		= "KES";
	$reference 		= $ref; //unique transaction id, generated by merchant.
	$callback_url 	= BASE_URL . 'redirect.php'; //URL user to be redirected to after payment

	// //Record order in your database.
	// $database = new pesapalDatabase();
	// $database->store($_POST);

    $payment -> storeOrder($ref,$auth -> get("user_id"),$reportInfo["report_id"],$reportInfo["report_price"]);

	$post_xml	= "<?xml version=\"1.0\" encoding=\"utf-8\"?>
				   <PesapalDirectOrderInfo
						xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
					  	xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"
					  	Currency=\"".$currency."\"
					  	Amount=\"".$amount."\"
					  	Description=\"".$desc."\"
					  	Type=\"".$type."\"
					  	Reference=\"".$reference."\"
					  	FirstName=\"".$first_name."\"
					  	LastName=\"".$last_name."\"
					  	Email=\"".$email."\"
					  	xmlns=\"http://www.pesapal.com\" />";
	$post_xml = htmlentities($post_xml);

	//post transaction to pesapal
	$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
	$iframe_src->set_parameter("oauth_callback", $callback_url);
	$iframe_src->set_parameter("pesapal_request_data", $post_xml);
	$iframe_src->sign_request($signature_method, $consumer, $token);



?>

<h2>Payment form</h2>
<div class="row-fluid">
    <div class="span4">
        <ol type="1">
        <li>At this point, its best you store the payment details inyour DB. Set the transaction status as PLACED</li>
        <li>The iframe with the payment options is a page from our PesaPal server. Its secured and is available over a secure https link</li>
        <li>It's not Mandatory to purchase the SSL certificate for your site</li>
        </ol>
    </div>

    <div id="rightcol2" class="span8">
        <iframe src="<?php echo $iframe_src;?>" width="100%" height="700px"  scrolling="no" frameBorder="0">
        	<p>Browser unable to load iFrame</p>
        </iframe>
    </div>
</div>


<?php require_once("footer.php"); ?>
